### ISSUE TITLE
Nothing is exported

### ISSUE THREAD

**Issue by tmtvl** [rgc69/si-kanren#1]
You may have forgotten to add... everything to your exports. By 'everything' I mean things like fresh, ==, conde,...

**Comment by rgc69** [comment]
Hi Tim!
Thank you for bringing to my attention the issue with the code in your
email. I appreciate your prompt response and assistance.

I usually  change the package I'm in, with (in-package :si-kanren ), just
to be sure to not messing up any symbols with the current package (usually
the common-lisp-user package). However, I wanted to seek your input on
whether this approach addresses the issue or if you recommend the
alternative solution.

Your guidance is highly valued, and I look forward to hearing your thoughts
on this matter.

Best regards,
Roberto

Il mer 24 gen 2024, 14:50 Tim Van den Langenbergh ***@***.***>
ha scritto:

**Comment by tmtvl** [comment]
Hey Roberto, yeah, that's one way of doing things, but there is an obvious problem with it: if I go and build something with sī-kanren and someone else (Person B) does the same, then a third person (Person C) will have a hard time using my and Person B's code in another project as they would have to somehow merge the two extended sī-kanren modules.

Messing up any existing symbols isn't really something to be worried about, because CL has namespaces, so if you export, say, == then someone could use it through the si-kanren:== name.

I do appreciate that managing namespaces can be hard (Alexandria has infamously had issues with that), but your worries may be a bit overblown. It's good of you to be careful though.

I hope this was of interest and/or value.

Vale,
- Tim

**Comment by rgc69** [comment]
Thank you for your feedback, Tim, really appreciated! Yes, I remember a quote in `Let over Lambda` [[1]](#1) about the argument at hand:  
> There are two ways to look at macros and namespaces. The first is that single namespace is of fundamental importance, and therefore macros are problematic. The second is that macros are fundamental, and therefore a single namespace is problematic. [[2]](#2).  :grin: 

I exported the main functionalities as per your recommendations, and I hope this is enough, but let me  know. Thank you once again,
Cheers,
Roberto

## References
<a id="1">[1]</a> 
Doug Hoyte (2008)
Let Over Lambda

<a id="2">[2]</a> 
Richard Gabriel, Kent Pitman (1988). 
International Journal on Lisp and Symbolic Computation: Technical issues of separation in function cells and value cells

**Comment by tmtvl** [comment]
Yep, this seems fine, thanks!
